modules/admin_old/models/PrCategory.php
<?php

namespace app\modules\admin\models;

use Yii;
use yii\helpers\ArrayHelper;
use app\components\MultilingualBehavior;
use app\components\MultilingualQuery;

/**
 * This is the model class for table "pr_category".
 *
 * @property integer $id
 * @property string $title
 * @property integer $parent_id
 */
class PrCategory extends \yii\db\ActiveRecord
{
    private static $tree = [];
    public static $tree_list = [];
    public static $child_full_tree = [];
    public static $child_tree = [];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pr_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'link'], 'required'],
            [['parent_id', 'sort_order', 'hidden'], 'integer'],
            [['title', 'image', 'image2', 'link'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'image' => 'Изображение',
            'image2' => 'Изображение 2',
            'image_filter' => 'Изображение фильтра',
            'image_filter_active' => 'Изображение активного фильтра',
            'sort_order' => 'Сортировка',
            'link' => 'Ссылка',
            'parent_id' => 'Родитель',
            'hidden' => 'Скрыта',
        ];
    }

    public function behaviors()
    {
        return [
            'ml' => [
                'class' => MultilingualBehavior::className(),
                'languages' => Lang::getBehaviorsList(),
                //'languageField' => 'language',
                //'localizedPrefix' => '',
                //'requireTranslations' => false',
                //'dynamicLangClass' => true',
                'defaultLanguage' => Lang::getCurrent()->local,
                'langForeignKey' => 'pr_category_id',
                'tableName' => "{{%pr_category_lang}}",
                'attributes' => [
                    'title'
                ]
            ],      
        ];
    }   

    public function getPar() {
        return $this->hasOne(self::className(), ['id' => 'parent_id']);
    }       
    
    public static function find()
    {
        $q = new MultilingualQuery(get_called_class());
        $q->localized();
        return $q;
    }     

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->link !== '/') {
                $this->link = str_replace(' ', '-', trim(trim($this->link, '/'))); 
            }
            $this->sort_order = !empty($this->sort_order)?intval($this->sort_order):0;
                       
            return true;
        }
        return false;
    }  

    public function beforeDelete()
    {
        if (!empty($this->image) && file_exists($_SERVER['DOCUMENT_ROOT'].'/web'.$this->image)) {
            unlink($_SERVER['DOCUMENT_ROOT'].'/web'.$this->image);
        }
        if (!empty($this->image2) && file_exists($_SERVER['DOCUMENT_ROOT'].'/web'.$this->image2)) {
            unlink($_SERVER['DOCUMENT_ROOT'].'/web'.$this->image2);
        }
        
        return parent::beforeDelete();
    }    

    public static function setTree()
    {
        if (!count(self::$tree)) {
            $model = self::find()->orderBy('sort_order ASC')->asArray()->all();
            $t = [];
            foreach ($model as $item) {
                $item_cat = [
                    'id' => $item['id'],
                    'title' => $item['title'],
                    'parent_id' => !empty($item['parent_id'])?$item['parent_id']:0
                ];
                $t[$item['id']] = $item_cat;
            }

            self::$tree_list = $t;
            self::$tree = self::buildTree($t);
        }

        return self::$tree;
    }

    public static function getFullTree($id, $url = false, &$arr = []) {
        if (isset(self::$tree_list[$id])) {
            $e = self::$tree_list[$id];
            self::$child_tree[] = $e;
            $arr[] = ($url)?$e['link']:$e;
            self::getFullTree($e['parent_id'], $url, $arr);
        }

        return ($url)?implode('/', array_reverse($arr)):array_reverse($arr);
    }    

    private static function buildTree(array $elements, $parentId = 0, $depth = 0) {
        $branch = array();

        foreach ($elements as $k => $element) {
            if ($parentId == 0) {
                $depth = 0;
            }
            if ($element['parent_id'] == $parentId) {
                $children = self::buildTree($elements, $element['id'], $depth);
                $branch[$element['id']] = $element['title'];
                if ($children) {
                    $depth++;
                    $margin = str_repeat('__', $depth);
                    foreach ($children as $k => $v) {
                        $children[$k] = $margin.$v;
                    }
                    $branch = ArrayHelper::merge($branch, $children);
                }
            }
        }

        return $branch;
    }         
}

modules/admin_old/controllers/PrCategoryController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\PrValue;
use app\modules\admin\models\PrAttr;
use app\modules\admin\models\PrEnt;
use app\modules\admin\models\PrCategory;
use app\modules\admin\models\PrCategorySearch;
use app\modules\admin\components\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/**
 * PrCategoryController implements the CRUD actions for PrCategory model.
 */
class PrCategoryController extends Controller
{
	public $layout = "./sidebar";

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update'],
                        'allow' => true,
                        'roles' => ['admin', 'moderator'],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
		if (Yii::$app->request->isAjax) {
			$keys = (isset($_POST['keys']))?$_POST['keys']:[];
			if (count($keys) && Yii::$app->user->can('admin')) {
				foreach ($keys as $k => $v) {
					if (($model = PrCategory::findOne($v)) !== null) {
						$model->delete();
					}
				}
				return $this->redirect(['index']);
			}
		}
		
        $searchModel = new PrCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new PrCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PrCategory();
        $model->sort_order = 0;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PrCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Изменения сохранены');
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }      
    }

    /**
     * Deletes an existing PrCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PrCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PrCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */

    protected function findModel($id, $ml = true)
    {
        if ($ml) {
            $model = PrCategory::find()->where('id = :id', [':id' => $id])->multilingual()->one();
        } else {
            $model = PrCategory::findOne($id);
        }
        
        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }    
}

modules/admin_old/views/pr-category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use zxbodya\yii2\elfinder\ElFinderInput;
use zxbodya\yii2\elfinder\ElFinderWidget;
use zxbodya\yii2\tinymce\TinyMce;
use zxbodya\yii2\elfinder\TinyMceElFinder;
use app\modules\admin\models\Lang;
use app\modules\admin\models\PrCategory;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\PrCategory */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin(['options' => ['class' => 'form']]); ?>

	<?= $form->errorSummary($model, ['class' => 'alert-danger alert fade in']); ?>
	
	<div class="card">
		<div class="card-head style-primary">
			<header><i class="fa fa-edit"></i> <?= Html::encode($this->title) ?></header>
			<div class="tools">
				<?= Html::submitButton('<i class="fa fa-plus"></i>', ['class' => 'btn btn-floating-action btn-default-light']) ?>
				<?= Html::a('<i class="fa fa-reply"></i>', ['index'], ['class' => 'btn btn-floating-action btn-default-light']) ?>
			</div>
		</div>
		
		<div class="card-head">
			<ul class="nav nav-tabs" data-toggle="tabs">
				<li class="active"><a href="#tab1">Данные</a></li>
				<?php foreach (Lang::getBehaviorsList() as $k => $v) { ?>
					<li><a href="#<?= $k ?>"><?= $v ?></a></li>
				<?php } ?>
			</ul>
		</div>
		<div class="card-body tab-content">
			<div class="tab-pane active" id="tab1">
				<div class="card-body floating-label">
					<div class="row">
						<div class="col-sm-6">
							<div>
								<button onclick="$(this).parent().find('img').remove();$(this).parent().find('input').val('');" type="button" class="btn ink-reaction btn-icon-toggle btn-primary"><i class="fa fa-trash-o"></i></button>
								<?= Yii::$app->imageCache->img($_SERVER['DOCUMENT_ROOT'].'/web'.$model->image,'x20') ?>
							
								<?= $form->field($model, 'image')->widget(
									ElFinderInput::className(),
									[
										'connectorRoute' => 'el-finder/connector_products',
									]
								) ?>
							</div>

							<div>
								<button onclick="$(this).parent().find('img').remove();$(this).parent().find('input').val('');" type="button" class="btn ink-reaction btn-icon-toggle btn-primary"><i class="fa fa-trash-o"></i></button>
								<?= Yii::$app->imageCache->img($_SERVER['DOCUMENT_ROOT'].'/web'.$model->image2,'x50') ?>
							
								<?= $form->field($model, 'image2')->widget(
									ElFinderInput::className(),
									[
										'connectorRoute' => 'el-finder/connector_products',
									]
								) ?>
							</div>							

							<div>
								<button onclick="$(this).parent().find('img').remove();$(this).parent().find('input').val('');" type="button" class="btn ink-reaction btn-icon-toggle btn-primary"><i class="fa fa-trash-o"></i></button>
								<?= Yii::$app->imageCache->img($_SERVER['DOCUMENT_ROOT'].'/web'.$model->image_filter,'x20') ?>
							
								<?= $form->field($model, 'image_filter')->widget(
									ElFinderInput::className(),
									[
										'connectorRoute' => 'el-finder/connector_products',
									]
								) ?>
							</div>							

							<div>
								<button onclick="$(this).parent().find('img').remove();$(this).parent().find('input').val('');" type="button" class="btn ink-reaction btn-icon-toggle btn-primary"><i class="fa fa-trash-o"></i></button>
								<?= Yii::$app->imageCache->img($_SERVER['DOCUMENT_ROOT'].'/web'.$model->image_filter_active,'x20') ?>
							
								<?= $form->field($model, 'image_filter_active')->widget(
									ElFinderInput::className(),
									[
										'connectorRoute' => 'el-finder/connector_products',
									]
								) ?>
							</div>
						</div>
						<div class="col-sm-6">
							<?= $form->field($model, 'parent_id')->dropdownList(ArrayHelper::merge(['' => 'Нет'], PrCategory::setTree())); ?>
							
							<?= $form->field($model, 'hidden')->dropdownList([0 => 'Нет', 1 => 'Да']); ?>

							<?= $form->field($model, 'title', ['template' => '{input}{label}{error}{hint}'])->textInput(['maxlength' => true]) ?>

							<?= $form->field($model, 'sort_order', ['template' => '{input}{label}{error}{hint}'])->textInput(['maxlength' => true]) ?>

							<div class="row">
								<div class="col-sm-11">
									<?= $form->field($model, 'link', ['template' => '{input}{label}{error}{hint}'])->textInput(['maxlength' => true]) ?>
								</div>
								<div class="col-sm-1">
									<?= Html::a('<i class="fa fa-link"></i>', 'javascript:void(0);', ['class' => 'btn btn-floating-action btn-default-light', 'onclick' => "v=$('#prcategory-title').val();if(v!=''){tr=translit(v);$('#prcategory-link').val($('#parurl').val()+tr).addClass('dirty');}"]) ?>
									<input type="hidden" id="parurl" value="<?= (!empty($model->par->link))?trim($model->par->link, '/').'/':'' ?>">
								</div>
							</div>
						</div>
					</div>
					<div class="form-group">
					
					</div>
				</div>
			</div>	
			<?php foreach (Lang::getBehaviorsList() as $k => $v) { ?>
				<div class="tab-pane" id="<?= $k ?>">
					<div class="card-body floating-label">
						<div class="row">
							<div class="col-sm-6">
								<?= $form->field($model, 'title_'.$k, ['template' => '{input}{label}{error}{hint}'])->textInput(['maxlength' => true])->label($model->getAttributeLabel('title').' '.$v) ?>
							</div>													
						</div>
					</div>
				</div>
			<?php } ?>
		</div>	
		
		<div class="card-actionbar">
			<div class="card-actionbar-row">
				<?= Html::submitButton($model->isNewRecord ? 'Добавить запись' : 'Сохранить данные', ['class' => 'btn ink-reaction btn-raised btn-primary']) ?>
			</div>
		</div>
	</div>
	<em class="text-caption"><?= Html::encode($this->title) ?></em>	

<?php ActiveForm::end(); ?>

modules/admin_old/views/pr-category/create.php
<?php
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\PrCategory */

$this->title = 'Новая категория';
$this->params['breadcrumbs'][] = ['label' => 'Админ панель', 'url' => ['/admin']];
$this->params['breadcrumbs'][] = ['label' => 'Категории товаров', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div id="content">
	<section>
		<div class="section-header">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>		
		</div>	
		<div class="section-body contain-xlg">	
		
			<div class="row">
				<div class="col-lg-12">

					<?=  $this->render('_form', [
						'model' => $model,
					]) ?>
				
				</div>
			</div>
		
		</div>
	</section>
</div>

modules/admin_old/views/pr-category/index.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use yii\widgets\Breadcrumbs;
use app\modules\admin\models\PrCategory;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\PrCategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Категории товаров';
$this->params['breadcrumbs'][] = ['label' => 'Админ панель', 'url' => ['/admin']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div id="content">
	<section>
		<div class="section-header">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>			
		</div>
		<div class="section-body contain-xlg">

			<div class="card">

				<div class="card-head style-primary">
					<header><i class="fa fa-table"></i> <?= Html::encode($this->title) ?></header>
					<div class="tools">
						<?= Html::a('<i class="fa fa-plus"></i>', ['create'], ['class' => 'btn btn-floating-action btn-default-light']) ?>
						<?php if (Yii::$app->user->can('admin')) { ?>
							<?= Html::a('<i class="fa fa-fire"></i>', [''], [
								'class' => 'btn ink-reaction btn-floating-action btn-default-light',
								'onclick'=>"
									var keys = $('#grid').yiiGridView('getSelectedRows');
									if (keys!='') {
										if (confirm('Вы уверены, что хотите удалить выбранные элементы?')) {
											$.ajax({
												type : 'POST',
												data: {keys : keys},
												success : function(data) {}
											});
										}
									}
									return false;
								",
							]) ?>
						<?php } ?>
					</div>
				</div>

				<div class="card-body">

					<div class="row">
						<div class="col-lg-12">
							<h4></h4>
						</div>
						<div class="col-lg-12">

							<?= GridView::widget([
								'dataProvider' => $dataProvider,
								'id' => 'grid',
								'layout'=>"
									<div class='dataTables_info'>{summary}</div>
									<div class='card'>
										<div class='card-body no-padding'>
											<div class='table-responsive no-margin'>{items}</div>
										</div>
									</div>
									<div class='dataTables_paginate paging_simple_numbers'>{pager}</div>
								",		
								'tableOptions' => [
									'class' => 'table table-striped no-margin table-hover table-bordered',
								],	
								'filterModel' => $searchModel,
								'columns' => [
									//['class' => 'yii\grid\SerialColumn'],
									['class' => 'yii\grid\CheckboxColumn'],
									[
										'filter' => false,
										'format' => 'html',
										'value' => function($data) {  
											return Yii::$app->imageCache->img($_SERVER['DOCUMENT_ROOT'].'/web'.$data->image,'x20'); 
										},
									],
									[
										'filter' => false,
										'format' => 'html',
										'value' => function($data) {  
											return Yii::$app->imageCache->img($_SERVER['DOCUMENT_ROOT'].'/web'.$data->image2,'x50'); 
										},
									],									
									[
										'attribute' => 'title',
										'format' => 'url',
										'content' => function($data) {
											return Html::a($data->title, ['update', 'id' => $data->id]);
										}
									],
									'link',
									[
										'attribute' => 'parent_id',
										'filter' => ArrayHelper::merge([], PrCategory::setTree()),
										'content' => function($data) {
											return !empty($data->par->title)?$data->par->title:'Нет';
										}
									],
									'sort_order',
									[
										'attribute' => 'hidden',
										'filter' => [0 => 'Нет', 1 => 'Да'],
										'value' => function ($model, $index, $widget) {
											return ($model->hidden == 0)?'Нет':'Да';
										},
									],
									[
										'class' => 'yii\grid\ActionColumn',
										'contentOptions' => [ 
											'style' => Yii::$app->user->can('admin')?'width: 100px;':'width: 50px;'
										], 	
										'template' => Yii::$app->user->can('admin')?'{update} {delete}':'{update}',										
										'buttons' => [										
											'update' => function ($url, $model) {
												return Html::a('<button type="button" class="btn btn-icon-toggle"><i class="fa fa-pencil"></i></button>', $url);
											},											
											'delete' => function ($url, $model) {
												return Html::a('<button type="button" class="btn btn-icon-toggle"><i class="fa fa-trash-o"></i></button>', $url, ['data-confirm'=>'Вы уверены, что хотите удалить этот элемент?', 'data-method'=>'post', 'data-pjax'=>'0']);
											},
										]
									],
								],
							]); ?>
												
						</div>
					</div>	
				</div>

			</div>

		</div>
	</section>
</div>

modules/admin_old/views/pr-category/update.php
<?php
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use app\components\widgets\Alert;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\PrCategory */

$this->title = 'Редактирование категории: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Админ панель', 'url' => ['/admin']];
$this->params['breadcrumbs'][] = ['label' => 'Категории товаров', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование категории';
?>

<div id="content">
	<section>
		<div class="section-header">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>			
		</div>	
		<div class="section-body contain-xlg">	
		
			<div class="row">
				<div class="col-lg-12">
				
					<?= Alert::widget() ?>

					<?= $this->render('_form', [
						'model' => $model,
					]) ?>
				
				</div>
			</div>
		
		</div>
	</section>
</div>